# Generated by Django 2.2.5 on 2019-10-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerules',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kpbt.League'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kpbt.League'),
        ),
    ]
