# Generated by Django 2.2.5 on 2019-10-02 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_bowlingcenter_manager',
            new_name='is_center_manager',
        ),
        migrations.AlterField(
            model_name='weeklypairing',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league', to='kpbt.League', verbose_name='weekly_pairing'),
        ),
        migrations.DeleteModel(
            name='LeagueGame',
        ),
    ]
