# Generated by Django 2.2.5 on 2019-10-07 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_with_team', models.PositiveSmallIntegerField(default=0)),
                ('is_substitute', models.BooleanField(default=False)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='rosters',
        ),
        migrations.DeleteModel(
            name='TeamRosters',
        ),
        migrations.AddField(
            model_name='teamroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpbt.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(through='kpbt.TeamRoster', to=settings.AUTH_USER_MODEL),
        ),
    ]
