# Generated by Django 2.2.5 on 2019-10-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguerules',
            old_name='min_roster_size',
            new_name='playing_strength',
        ),
        migrations.AlterField(
            model_name='bowlerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='VACANT', max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(through='kpbt.TeamRoster', to='kpbt.BowlerProfile'),
        ),
        migrations.AlterField(
            model_name='teamroster',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpbt.BowlerProfile'),
        ),
    ]
