# Generated by Django 2.2.5 on 2019-11-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='weekly_points_lost',
        ),
        migrations.RemoveField(
            model_name='series',
            name='weekly_points_won',
        ),
        migrations.CreateModel(
            name='WeeklyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=0)),
                ('lane_pair', models.PositiveSmallIntegerField(default=0)),
                ('average', models.PositiveSmallIntegerField(default=0)),
                ('handicap', models.PositiveSmallIntegerField(default=0)),
                ('g1', models.PositiveSmallIntegerField(default=0)),
                ('g2', models.PositiveSmallIntegerField(default=0)),
                ('g3', models.PositiveSmallIntegerField(default=0)),
                ('series', models.PositiveSmallIntegerField(default=0)),
                ('points_won', models.PositiveSmallIntegerField(default=0)),
                ('points_lost', models.PositiveSmallIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpbt.League')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='kpbt.Team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpbt.Team')),
            ],
        ),
    ]
