# Generated by Django 2.2.5 on 2019-10-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0002_auto_20191007_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='bowling_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='kpbt.BowlingCenter', verbose_name='bowling center'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_handicap_pins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_pinfall',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_scratch_pins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
