# Generated by Django 2.2.5 on 2019-10-08 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpbt', '0002_auto_20191007_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_date', models.DateField()),
                ('applied_average', models.PositiveSmallIntegerField()),
                ('game_one_score', models.PositiveSmallIntegerField()),
                ('game_two_score', models.PositiveSmallIntegerField()),
                ('game_three_score', models.PositiveSmallIntegerField()),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpbt.League')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpbt.Team')),
            ],
        ),
    ]
