# Generated by Django 2.2.5 on 2019-10-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0002_auto_20191026_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlerprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('A', 'Adult'), ('S', 'Senior'), ('J', 'Junior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bowlerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bowlerprofile',
            name='hand',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teamroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_record', to='kpbt.Team'),
        ),
    ]
