# Generated by Django 2.2.5 on 2019-10-09 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0003_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlerprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_bowler',
            field=models.BooleanField(default=False),
        ),
    ]
