# Generated by Django 2.2.5 on 2019-10-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0003_auto_20191007_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
