# Generated by Django 2.2.5 on 2019-10-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0003_auto_20191026_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamroster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
