# Generated by Django 2.2.5 on 2019-10-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0004_auto_20191007_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowlingcenter',
            old_name='center_name',
            new_name='name',
        ),
    ]
