# Generated by Django 2.2.5 on 2019-10-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0004_auto_20191008_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlingcenter',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
