# Generated by Django 2.2.5 on 2019-10-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0005_auto_20191008_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='bowling_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='kpbt.BowlingCenter', verbose_name='bowling center'),
        ),
    ]
