# Generated by Django 2.2.5 on 2019-10-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0006_series_applied_handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
