# Generated by Django 2.2.5 on 2019-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0007_series_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguebowler',
            name='games_bowled',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
