# Generated by Django 2.2.5 on 2019-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0008_leaguebowler_games_bowled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguebowler',
            name='league_average',
        ),
        migrations.AlterField(
            model_name='leaguebowler',
            name='games_bowled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguebowler',
            name='league_high_game',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguebowler',
            name='league_high_series',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguebowler',
            name='league_total_handicap',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguebowler',
            name='league_total_scratch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
