# Generated by Django 2.2.5 on 2019-10-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0009_auto_20191030_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='game_one_score',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='series',
            name='game_three_score',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='series',
            name='game_two_score',
            field=models.CharField(max_length=4),
        ),
    ]
