# Generated by Django 2.2.5 on 2019-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0010_auto_20191030_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguebowler',
            old_name='league_high_game',
            new_name='league_average',
        ),
        migrations.RenameField(
            model_name='leaguebowler',
            old_name='league_high_series',
            new_name='league_high_handicap_game',
        ),
        migrations.AddField(
            model_name='leaguebowler',
            name='league_high_handicap_series',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguebowler',
            name='league_high_scratch_game',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguebowler',
            name='league_high_scratch_series',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
