# Generated by Django 2.2.5 on 2019-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0011_auto_20191030_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_points',
            new_name='team_points_won',
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='handicap_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_points_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='absentee_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='bye_team_point_threshold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='game_point_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='handicap_scratch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='max_roster_size',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='playing_strength',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='series_point_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
