# Generated by Django 2.2.5 on 2019-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0012_auto_20191031_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='weekly_points_lost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='weekly_points_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
