# Generated by Django 2.2.5 on 2019-11-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0013_auto_20191031_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
