# Generated by Django 2.2.5 on 2019-11-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0016_auto_20191107_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlerprofile',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='centeraddress',
            name='bowling_center',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='kpbt.BowlingCenter'),
            preserve_default=False,
        ),
    ]
