# Generated by Django 2.2.5 on 2019-11-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0018_auto_20191109_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='bowlerprofile',
            name='is_sanctioned',
        ),
        migrations.RemoveField(
            model_name='bowlerprofile',
            name='last_date_sanctioned',
        ),
    ]
