# Generated by Django 2.2.5 on 2019-11-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0019_auto_20191109_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='current_week',
        ),
        migrations.CreateModel(
            name='WeeklyPairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=0)),
                ('lane_pair', models.PositiveSmallIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='kpbt.League')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpbt.Team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpbt.Team')),
            ],
        ),
    ]
