# Generated by Django 2.2.5 on 2019-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0020_auto_20191111_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
