# Generated by Django 2.2.5 on 2019-11-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0021_league_current_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypairings',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_pair', to='kpbt.Team'),
        ),
        migrations.AlterField(
            model_name='weeklypairings',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_pair', to='kpbt.Team'),
        ),
    ]
