# Generated by Django 2.2.5 on 2019-11-11 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpbt', '0022_auto_20191111_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='secretary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
