# Generated by Django 2.2.5 on 2019-11-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0014_auto_20191107_1714'),
        ('kpbt', '0023_league_secretary'),
    ]

    operations = [
    ]
