# Generated by Django 2.2.5 on 2019-11-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0024_merge_20191111_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
