# Generated by Django 2.2.5 on 2019-11-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0025_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguerules',
            name='allow_substitutes',
        ),
    ]
