# Generated by Django 2.2.5 on 2019-11-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0024_merge_20191112_0253'),
        ('kpbt', '0026_remove_leaguerules_allow_substitutes'),
    ]

    operations = [
    ]
