# Generated by Django 2.2.5 on 2019-11-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0027_merge_20191112_1840'),
        ('kpbt', '0027_merge_20191112_2324'),
    ]

    operations = [
    ]
