# Generated by Django 2.2.5 on 2019-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0028_merge_20191115_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='week_pointer',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
