# Generated by Django 2.2.5 on 2019-11-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0028_merge_20191113_1625'),
        ('kpbt', '0029_league_week_pointer'),
    ]

    operations = [
    ]
