# Generated by Django 2.2.5 on 2019-11-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0030_merge_20191118_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamroster',
            name='is_substitute',
        ),
    ]
