# Generated by Django 2.2.5 on 2019-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0031_remove_teamroster_is_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerules',
            name='entering_average',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
