# Generated by Django 2.2.5 on 2019-11-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0030_merge_20191119_0049'),
        ('kpbt', '0031_remove_teamroster_is_substitute'),
    ]

    operations = [
    ]
