# Generated by Django 2.2.5 on 2019-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0032_leaguerules_entering_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='handicap_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='scratch_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='designation',
            field=models.CharField(choices=[('A', 'Adult'), ('S', 'Senior'), ('J', 'Junior'), ('N', 'Any')], max_length=1),
        ),
    ]
