# Generated by Django 2.2.5 on 2019-11-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0032_leaguerules_entering_average'),
        ('kpbt', '0032_merge_20191119_2240'),
    ]

    operations = [
    ]
