# Generated by Django 2.2.5 on 2019-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0033_auto_20191121_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='applied_average',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='applied_handicap',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='game_one_score',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='series',
            name='game_three_score',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='series',
            name='game_two_score',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='series',
            name='pair_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='series',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
