# Generated by Django 2.2.5 on 2019-11-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpbt', '0033_merge_20191122_0400'),
        ('kpbt', '0034_auto_20191124_0259'),
    ]

    operations = [
    ]
